### PR TITLE
Adding Gitlab support and setting Max concurrencies

### PR DESCRIPTION
**Pull request by vachanalaviswanath**

### CODE REVIEW

**Comment by LivingInSyn** [comment]
@vachanalaviswanath I made some changes, can you let me know when you run the gitlab tests and I'll verify github?

**Comment by LivingInSyn** [comment]
One thing I forgot, we need to update the README as well

**Comment by LivingInSyn** [comment]
fixed two bugs

1) If you only configure github or gitlab, it threw a fatal error in `getPats`
2) github wasn't actually respecting the 'get me all repos' functionality of a <0 days old var, fixed it. Also discovered a bug because I assumed github paging starting at 0, it starts at 1, resulting in duplicate entries (page 0 and page 1 return the same results)

**Comment by vachanalaviswanath** [comment]
> @vachanalaviswanath I made some changes, can you let me know when you run the gitlab tests and I'll verify github?

@LivingInSyn I have tested the gitlab and scan looks good to me. Thanks for refactoring my piece :)

**Pull request merged**
